<a href="https://colab.research.google.com/github/ralsouza/data_visualization_with_python/blob/master/notebooks/06_python_numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

In [0]:
import numpy as np
np.__version__

'1.18.3'

In [0]:
# Make an array with Numpy
arr1 = np.arange(0,15); arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
# Help
?arr1

In [0]:
# Calculating the mean of items
arr1.mean()

7.0

In [0]:
# Sum items
arr1.sum()

105

In [0]:
# Fetch minimal value
arr1.min()

0

In [0]:
# Fetch maximum value
arr1.max()

14

In [0]:
# calculating the standard deviation
arr1.std()

4.320493798938574

# List Comprehension


In [0]:
# FOR each item IN arr1, multiply x by itself
[x * x for x in arr1]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [0]:
# FOR each item IN arr1, multiply x by itself IF the division by 2 is equal 0
[x * x for x in arr1 if x % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

#Lamdba Functions

In [0]:
list(filter(lambda x: x % 2 == 0, arr1))

[0, 2, 4, 6, 8, 10, 12, 14]

In [0]:
arr1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [0]:
# Make the same if numpy and slice notation
arr1[arr1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

# Measuring the performance

In [0]:
# Using list comprehension
%timeit [x for x in arr1 if x % 2 == 0]

The slowest run took 22.29 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 9.12 µs per loop


In [0]:
# Using numpy
%timeit arr1[arr1 % 2 == 0]

The slowest run took 46.98 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.76 µs per loop


# Logic Operator with NumPy

In [0]:
# Notation like map() function
arr1 > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [0]:
# Notation like filter() function
arr1[arr1 > 8]

array([ 9, 10, 11, 12, 13, 14])

In [0]:
# And Operator
(arr1 > 9) & (arr1 < 12)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False])

In [0]:
# Or Operator
(arr1 > 13) | (arr1 < 12)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True])

In [0]:
# Or operator with slice notation
arr1[(arr1 > 13) | (arr1 < 12)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 14])

In [0]:
# Making arrays with numpy and list comprehension
arr2 = np.array([x ** 3 for x in range(15)]); arr2

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

In [0]:
# making arrays with list comprehension and boolean values
arr3 = np.array([True for x in range(15)]); arr3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [0]:
# Using an array as index in another
arr1[arr2]

IndexError: ignored