<a href="https://colab.research.google.com/github/ralsouza/data_visualization_with_python/blob/master/notebooks/07_python_numpy_arrays_SplitApplyCombine_concatenation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

# Concatenating

In [0]:
arr1 = np.ones(4); arr1

array([1., 1., 1., 1.])

In [0]:
arr2 = np.arange(15); arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
# Concatenating arr1 and arr2
concat_arr = np.concatenate((arr1,arr2)); concat_arr

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])