<a href="https://colab.research.google.com/github/ralsouza/data_visualization_with_python/blob/master/notebooks/08_python_SplitApplyCombine_arrays_joining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#Joining

In [3]:
arr1 = np.ones((3,3)); arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr2 = np.zeros((3,3)); arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
# Stack arrays in sequence vertically (row wise)
# This function makes most sense for arrays with up to 3 dimensions
?np.vstack

In [0]:
# Stack arrays in sequence horizontally (column wise)
# This function makes most sense for arrays with up to 3 dimensions
?np.hstack

In [10]:
# Stacking vertically
np.vstack((arr1,arr2))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# Stacking horizontally
np.hstack((arr1,arr2))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [0]:
# Stacking arrays with 1-D and 2-D
x = np.array([0,1,2])
y = np.array([3,4,5])
z = np.array([6,7,8])

In [0]:
# Stack 1-D arrays as columns into a 2-D array
?np.column_stack

In [0]:
# Stack arrays in sequence vertically (row wise)
# This is equivalent to concatenation along the first axis after 1-D arrays
?np.row_stack

In [18]:
# Stacking by column
np.column_stack((x,y,z))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [19]:
# Stacking by row
np.row_stack((x,y,z))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])