<a href="https://colab.research.google.com/github/ralsouza/data_visualization_with_python/blob/master/notebooks/09_python_numpy_arrays_SplitApplyCombine_splitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

#Splitting

In [7]:
arr1 = np.arange(16).reshape((4,4)); arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
# Splitting arr1 horizontally in 2 parts
[arr1_h_p1, arr1_h_p2] = np.hsplit(arr1,2)

In [14]:
# Show part 1
arr1_h_p1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [15]:
# Show part 2
arr1_h_p2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [0]:
# Splitting arr1 vertically in 2 parts
[arr1_v_p1, arr1_v_p2] = np.vsplit(arr1,2)

In [17]:
# Show part 1
arr1_v_p1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [18]:
# Show part 2
arr1_v_p2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])