<a href="https://colab.research.google.com/github/ralsouza/data_visualization_with_python/blob/master/notebooks/11_python_numpy_mathematical_operations_arrays_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [2]:
# making a matrix with ; notation
mt1 = np.matrix('1,2,3 ; 4,5,6'); mt1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [3]:
# Check typr
type(mt1)

numpy.matrix

In [5]:
# Making another matrix with brackets notation
mat2 = np.matrix([[1,2,3],[4,5,6]]); mat2

matrix([[1, 2, 3],
        [4, 5, 6]])

In [6]:
mat3 = np.matrix([[0,10,0,0,0], [0,0,20,0,0], [0,0,0,30,0], [0,0,0,0,40], [0,0,0,0,0]]); mat3

matrix([[ 0, 10,  0,  0,  0],
        [ 0,  0, 20,  0,  0],
        [ 0,  0,  0, 30,  0],
        [ 0,  0,  0,  0, 40],
        [ 0,  0,  0,  0,  0]])

In [8]:
# Check type
type(mat3)

numpy.matrix

In [7]:
# Slicing mat3 by position
mat3[2,3]

30

# Operations with Arrays and Matrices

In [9]:
a = np.array([[1,2], [3,4]]); a

array([[1, 2],
       [3, 4]])

In [10]:
type(a)

numpy.ndarray

In [11]:
# Multiply a with a
a * a

array([[ 1,  4],
       [ 9, 16]])

In [12]:
# Converting a to matrix data type
A = np.mat(a); A

matrix([[1, 2],
        [3, 4]])

In [13]:
type(A)

numpy.matrix

In [15]:
# Multiply A with A with dot product
# Multiplying matrices is different from arrays, arrays is multiplied with same positions and matrices is row by column (dot product)
A * A

matrix([[ 7, 10],
        [15, 22]])

In [16]:
# Multiply two arrays by dot product
np.dot(a,a)

array([[ 7, 10],
       [15, 22]])